################################# Default configuration ###################
baseURL = "https://resolverestoration.com"
title = "Resolve Restoration"
theme = "meghna-hugo"

# post pagination
paginate = "6"
# post excerpt
summaryLength = "15"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = ["fr"]

############################# Plugins ##########################
# css plugins.
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/fontawesome/all.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Anaheim|Quattrocento+Sans:400,700&display=swap"

# js plugins
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/fontawesome/all.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/lazy-load/lozad.min.js"

################### English Navigation ########################
[[Languages.en.menu.main]]
name = "About"
url = "#about"
weight = 1

[[Languages.en.menu.main]]
name = "Services"
url = "#services"
weight = 2

[[Languages.en.menu.main]]
name = "Our Clients"
url = "#portfolio"
weight = 3

[[Languages.en.menu.main]]
name = "Contact Us"
url = "#contact"
weight = 4

[[Languages.en.menu.main]]
name = "Get a Quote"
url = "https://forms.gle/wkwhCt3TsKPKBTfs8"
weight = 5

[[Languages.en.menu.main]]
name = "Emergency Line: 604-368-6061"
url = "tel:6043686061"
weight = 6


############################# Default Parameters ##########################
[params]
logo = "images/resolve-restoration.jpg"
# Meta data
description = "Resolve Restoration Canada"
# Google Analytics
# google_analytics_id = "" # Your ID
# post share
post_share = true
copyright = "Copyright &copy; 2023"
[params.author]
author = "Resolve Restoration"
email = "said@centrumconcierge.com"
# preloader
[params.preloader]
enable = false
preloader = "images/logo.png"

# cookies
[params.cookies]
enable = false
expire_days = 2

############################# social icons ##########################
# [[params.social]]
# icon = "ti-facebook" # themify icon pack : https://themify.me/themify-icons
# link = "#"

# [[params.social]]
# icon = "ti-twitter-alt" # themify icon pack : https://themify.me/themify-icons
# link = "#"

# [[params.social]]
# icon = "ti-linkedin" # themify icon pack : https://themify.me/themify-icons
# link = "#"

################################ English Language ########################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
home = "Home"
copyright = "Copyright &copy; 2023 Resolve Restoration Canada"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
